import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

interface WordData {
  english: string;
  russian: string;
  examples: Array<{ sentence: string; translation?: string }>;
}

const animalsWords: WordData[] = [
  { english: 'dog', russian: 'собака', examples: [{ sentence: 'The dog is barking loudly.', translation: 'Собака громко лает.' }] },
  { english: 'cat', russian: 'кошка', examples: [{ sentence: 'My cat loves to sleep on the sofa.', translation: 'Моя кошка любит спать на диване.' }] },
  { english: 'elephant', russian: 'слон', examples: [{ sentence: 'The elephant is the largest land animal.', translation: 'Слон - самое крупное наземное животное.' }] },
  { english: 'tiger', russian: 'тигр', examples: [{ sentence: 'Tigers live in Asia.', translation: 'Тигры живут в Азии.' }] },
  { english: 'lion', russian: 'лев', examples: [{ sentence: 'The lion is called the king of the jungle.', translation: 'Льва называют царем джунглей.' }] },
  { english: 'bear', russian: 'медведь', examples: [{ sentence: 'Bears hibernate in winter.', translation: 'Медведи впадают в спячку зимой.' }] },
  { english: 'wolf', russian: 'волк', examples: [{ sentence: 'Wolves hunt in packs.', translation: 'Волки охотятся стаями.' }] },
  { english: 'fox', russian: 'лиса', examples: [{ sentence: 'The fox is very cunning.', translation: 'Лиса очень хитрая.' }] },
  { english: 'rabbit', russian: 'кролик', examples: [{ sentence: 'Rabbits love to eat carrots.', translation: 'Кролики любят есть морковь.' }] },
  { english: 'horse', russian: 'лошадь', examples: [{ sentence: 'The horse runs very fast.', translation: 'Лошадь бегает очень быстро.' }] },
  { english: 'cow', russian: 'корова', examples: [{ sentence: 'Cows give us milk.', translation: 'Коровы дают нам молоко.' }] },
  { english: 'pig', russian: 'свинья', examples: [{ sentence: 'Pigs are intelligent animals.', translation: 'Свиньи - умные животные.' }] },
  { english: 'sheep', russian: 'овца', examples: [{ sentence: 'Sheep provide us with wool.', translation: 'Овцы дают нам шерсть.' }] },
  { english: 'goat', russian: 'коза', examples: [{ sentence: 'Goats can climb steep hills.', translation: 'Козы могут взбираться на крутые холмы.' }] },
  { english: 'chicken', russian: 'курица', examples: [{ sentence: 'Chickens lay eggs.', translation: 'Куры несут яйца.' }] },
  { english: 'duck', russian: 'утка', examples: [{ sentence: 'Ducks swim in the pond.', translation: 'Утки плавают в пруду.' }] },
  { english: 'goose', russian: 'гусь', examples: [{ sentence: 'Geese fly south in winter.', translation: 'Гуси улетают на юг зимой.' }] },
  { english: 'turkey', russian: 'индейка', examples: [{ sentence: 'Turkey is served on Thanksgiving.', translation: 'Индейку подают на День благодарения.' }] },
  { english: 'parrot', russian: 'попугай', examples: [{ sentence: 'Parrots can imitate human speech.', translation: 'Попугаи могут имитировать человеческую речь.' }] },
  { english: 'owl', russian: 'сова', examples: [{ sentence: 'Owls are nocturnal birds.', translation: 'Совы - ночные птицы.' }] },
  { english: 'eagle', russian: 'орел', examples: [{ sentence: 'Eagles have excellent eyesight.', translation: 'У орлов отличное зрение.' }] },
  { english: 'hawk', russian: 'ястреб', examples: [{ sentence: 'The hawk caught a mouse.', translation: 'Ястреб поймал мышь.' }] },
  { english: 'sparrow', russian: 'воробей', examples: [{ sentence: 'Sparrows live near humans.', translation: 'Воробьи живут рядом с людьми.' }] },
  { english: 'pigeon', russian: 'голубь', examples: [{ sentence: 'Pigeons are common in cities.', translation: 'Голуби часто встречаются в городах.' }] },
  { english: 'crow', russian: 'ворона', examples: [{ sentence: 'Crows are very smart birds.', translation: 'Вороны - очень умные птицы.' }] },
  { english: 'swan', russian: 'лебедь', examples: [{ sentence: 'Swans are graceful birds.', translation: 'Лебеди - грациозные птицы.' }] },
  { english: 'penguin', russian: 'пингвин', examples: [{ sentence: 'Penguins cannot fly.', translation: 'Пингвины не умеют летать.' }] },
  { english: 'dolphin', russian: 'дельфин', examples: [{ sentence: 'Dolphins are very intelligent mammals.', translation: 'Дельфины - очень умные млекопитающие.' }] },
  { english: 'whale', russian: 'кит', examples: [{ sentence: 'Blue whales are the largest animals on Earth.', translation: 'Синие киты - крупнейшие животные на Земле.' }] },
  { english: 'shark', russian: 'акула', examples: [{ sentence: 'Sharks have been around for millions of years.', translation: 'Акулы существуют миллионы лет.' }] },
  { english: 'fish', russian: 'рыба', examples: [{ sentence: 'Fish breathe through gills.', translation: 'Рыбы дышат жабрами.' }] },
  { english: 'octopus', russian: 'осьминог', examples: [{ sentence: 'Octopuses have eight arms.', translation: 'У осьминогов восемь щупалец.' }] },
  { english: 'jellyfish', russian: 'медуза', examples: [{ sentence: 'Jellyfish can sting.', translation: 'Медузы могут жалить.' }] },
  { english: 'crab', russian: 'краб', examples: [{ sentence: 'Crabs walk sideways.', translation: 'Крабы ходят боком.' }] },
  { english: 'lobster', russian: 'лобстер', examples: [{ sentence: 'Lobster is a delicacy.', translation: 'Лобстер - деликатес.' }] },
  { english: 'shrimp', russian: 'креветка', examples: [{ sentence: 'Shrimp are popular seafood.', translation: 'Креветки - популярные морепродукты.' }] },
  { english: 'turtle', russian: 'черепаха', examples: [{ sentence: 'Sea turtles live very long.', translation: 'Морские черепахи живут очень долго.' }] },
  { english: 'frog', russian: 'лягушка', examples: [{ sentence: 'Frogs can jump very far.', translation: 'Лягушки могут прыгать очень далеко.' }] },
  { english: 'snake', russian: 'змея', examples: [{ sentence: 'Some snakes are venomous.', translation: 'Некоторые змеи ядовиты.' }] },
  { english: 'lizard', russian: 'ящерица', examples: [{ sentence: 'Lizards like to sunbathe.', translation: 'Ящерицы любят греться на солнце.' }] },
  { english: 'crocodile', russian: 'крокодил', examples: [{ sentence: 'Crocodiles are dangerous predators.', translation: 'Крокодилы - опасные хищники.' }] },
  { english: 'alligator', russian: 'аллигатор', examples: [{ sentence: 'Alligators live in swamps.', translation: 'Аллигаторы живут в болотах.' }] },
  { english: 'monkey', russian: 'обезьяна', examples: [{ sentence: 'Monkeys love bananas.', translation: 'Обезьяны любят бананы.' }] },
  { english: 'gorilla', russian: 'горилла', examples: [{ sentence: 'Gorillas are very strong.', translation: 'Гориллы очень сильные.' }] },
  { english: 'chimpanzee', russian: 'шимпанзе', examples: [{ sentence: 'Chimpanzees use tools.', translation: 'Шимпанзе используют орудия.' }] },
  { english: 'giraffe', russian: 'жираф', examples: [{ sentence: 'Giraffes have very long necks.', translation: 'У жирафов очень длинные шеи.' }] },
  { english: 'zebra', russian: 'зебра', examples: [{ sentence: 'Zebras have black and white stripes.', translation: 'У зебр черно-белые полосы.' }] },
  { english: 'hippopotamus', russian: 'бегемот', examples: [{ sentence: 'Hippos spend most time in water.', translation: 'Бегемоты проводят большую часть времени в воде.' }] },
  { english: 'rhinoceros', russian: 'носорог', examples: [{ sentence: 'Rhinos have thick skin.', translation: 'У носорогов толстая кожа.' }] },
  { english: 'kangaroo', russian: 'кенгуру', examples: [{ sentence: 'Kangaroos carry babies in pouches.', translation: 'Кенгуру носят детенышей в сумках.' }] },
  { english: 'koala', russian: 'коала', examples: [{ sentence: 'Koalas eat eucalyptus leaves.', translation: 'Коалы едят листья эвкалипта.' }] },
  { english: 'panda', russian: 'панда', examples: [{ sentence: 'Pandas love bamboo.', translation: 'Панды любят бамбук.' }] },
  { english: 'deer', russian: 'олень', examples: [{ sentence: 'Deer have antlers.', translation: 'У оленей есть рога.' }] },
  { english: 'moose', russian: 'лось', examples: [{ sentence: 'Moose are the largest deer species.', translation: 'Лоси - самый крупный вид оленей.' }] },
  { english: 'camel', russian: 'верблюд', examples: [{ sentence: 'Camels can survive without water for days.', translation: 'Верблюды могут выживать без воды несколько дней.' }] },
  { english: 'donkey', russian: 'осел', examples: [{ sentence: 'Donkeys are hardworking animals.', translation: 'Ослы - трудолюбивые животные.' }] },
  { english: 'squirrel', russian: 'белка', examples: [{ sentence: 'Squirrels collect nuts for winter.', translation: 'Белки собирают орехи на зиму.' }] },
  { english: 'hedgehog', russian: 'еж', examples: [{ sentence: 'Hedgehogs have sharp spines.', translation: 'У ежей острые иголки.' }] },
  { english: 'bat', russian: 'летучая мышь', examples: [{ sentence: 'Bats are the only flying mammals.', translation: 'Летучие мыши - единственные летающие млекопитающие.' }] },
  { english: 'mouse', russian: 'мышь', examples: [{ sentence: 'Mice are small rodents.', translation: 'Мыши - маленькие грызуны.' }] },
  { english: 'rat', russian: 'крыса', examples: [{ sentence: 'Rats are very adaptable.', translation: 'Крысы очень приспособляемы.' }] },
  { english: 'hamster', russian: 'хомяк', examples: [{ sentence: 'Hamsters store food in their cheeks.', translation: 'Хомяки хранят еду в щеках.' }] },
  { english: 'beaver', russian: 'бобр', examples: [{ sentence: 'Beavers build dams.', translation: 'Бобры строят плотины.' }] },
  { english: 'otter', russian: 'выдра', examples: [{ sentence: 'Otters are playful animals.', translation: 'Выдры - игривые животные.' }] },
  { english: 'seal', russian: 'тюлень', examples: [{ sentence: 'Seals live in cold waters.', translation: 'Тюлени живут в холодных водах.' }] },
  { english: 'walrus', russian: 'морж', examples: [{ sentence: 'Walruses have long tusks.', translation: 'У моржей длинные бивни.' }] },
  { english: 'polar bear', russian: 'белый медведь', examples: [{ sentence: 'Polar bears live in the Arctic.', translation: 'Белые медведи живут в Арктике.' }] },
  { english: 'leopard', russian: 'леопард', examples: [{ sentence: 'Leopards are excellent climbers.', translation: 'Леопарды отлично лазают.' }] },
  { english: 'cheetah', russian: 'гепард', examples: [{ sentence: 'Cheetahs are the fastest land animals.', translation: 'Гепарды - самые быстрые наземные животные.' }] },
  { english: 'jaguar', russian: 'ягуар', examples: [{ sentence: 'Jaguars live in South America.', translation: 'Ягуары живут в Южной Америке.' }] },
  { english: 'hyena', russian: 'гиена', examples: [{ sentence: 'Hyenas have a distinctive laugh.', translation: 'У гиен характерный смех.' }] },
  { english: 'antelope', russian: 'антилопа', examples: [{ sentence: 'Antelopes run very fast.', translation: 'Антилопы бегают очень быстро.' }] },
  { english: 'buffalo', russian: 'буйвол', examples: [{ sentence: 'Buffaloes live in herds.', translation: 'Буйволы живут стадами.' }] },
  { english: 'bison', russian: 'бизон', examples: [{ sentence: 'Bison once roamed North America.', translation: 'Бизоны когда-то бродили по Северной Америке.' }] },
  { english: 'yak', russian: 'як', examples: [{ sentence: 'Yaks live in mountains.', translation: 'Яки живут в горах.' }] },
  { english: 'llama', russian: 'лама', examples: [{ sentence: 'Llamas are used as pack animals.', translation: 'Лам используют как вьючных животных.' }] },
  { english: 'alpaca', russian: 'альпака', examples: [{ sentence: 'Alpacas have soft wool.', translation: 'У альпак мягкая шерсть.' }] },
  { english: 'flamingo', russian: 'фламинго', examples: [{ sentence: 'Flamingos are pink birds.', translation: 'Фламинго - розовые птицы.' }] },
  { english: 'peacock', russian: 'павлин', examples: [{ sentence: 'Peacocks have beautiful tails.', translation: 'У павлинов красивые хвосты.' }] },
  { english: 'pelican', russian: 'пеликан', examples: [{ sentence: 'Pelicans have large beaks.', translation: 'У пеликанов большие клювы.' }] },
  { english: 'stork', russian: 'аист', examples: [{ sentence: 'Storks build large nests.', translation: 'Аисты строят большие гнезда.' }] },
  { english: 'heron', russian: 'цапля', examples: [{ sentence: 'Herons catch fish.', translation: 'Цапли ловят рыбу.' }] },
  { english: 'seagull', russian: 'чайка', examples: [{ sentence: 'Seagulls live near the sea.', translation: 'Чайки живут у моря.' }] },
  { english: 'butterfly', russian: 'бабочка', examples: [{ sentence: 'Butterflies have colorful wings.', translation: 'У бабочек красочные крылья.' }] },
  { english: 'bee', russian: 'пчела', examples: [{ sentence: 'Bees make honey.', translation: 'Пчелы делают мед.' }] },
  { english: 'wasp', russian: 'оса', examples: [{ sentence: 'Wasps can sting multiple times.', translation: 'Осы могут жалить несколько раз.' }] },
  { english: 'ant', russian: 'муравей', examples: [{ sentence: 'Ants live in colonies.', translation: 'Муравьи живут колониями.' }] },
  { english: 'spider', russian: 'паук', examples: [{ sentence: 'Spiders spin webs.', translation: 'Пауки плетут паутину.' }] },
  { english: 'beetle', russian: 'жук', examples: [{ sentence: 'Beetles have hard shells.', translation: 'У жуков твердые панцири.' }] },
  { english: 'dragonfly', russian: 'стрекоза', examples: [{ sentence: 'Dragonflies fly very fast.', translation: 'Стрекозы летают очень быстро.' }] },
  { english: 'grasshopper', russian: 'кузнечик', examples: [{ sentence: 'Grasshoppers can jump high.', translation: 'Кузнечики могут высоко прыгать.' }] },
  { english: 'caterpillar', russian: 'гусеница', examples: [{ sentence: 'Caterpillars become butterflies.', translation: 'Гусеницы становятся бабочками.' }] },
  { english: 'snail', russian: 'улитка', examples: [{ sentence: 'Snails move very slowly.', translation: 'Улитки двигаются очень медленно.' }] },
  { english: 'worm', russian: 'червь', examples: [{ sentence: 'Worms live in soil.', translation: 'Черви живут в почве.' }] },
  { english: 'starfish', russian: 'морская звезда', examples: [{ sentence: 'Starfish have five arms.', translation: 'У морских звезд пять лучей.' }] },
  { english: 'seahorse', russian: 'морской конек', examples: [{ sentence: 'Seahorses are unusual fish.', translation: 'Морские коньки - необычные рыбы.' }] },
  { english: 'clam', russian: 'моллюск', examples: [{ sentence: 'Clams live in shells.', translation: 'Моллюски живут в раковинах.' }] },
];

const geographyWords: WordData[] = [
  { english: 'mountain', russian: 'гора', examples: [{ sentence: 'The mountain is covered with snow.', translation: 'Гора покрыта снегом.' }] },
  { english: 'river', russian: 'река', examples: [{ sentence: 'The river flows to the sea.', translation: 'Река течет к морю.' }] },
  { english: 'ocean', russian: 'океан', examples: [{ sentence: 'The Pacific Ocean is the largest.', translation: 'Тихий океан - самый большой.' }] },
  { english: 'sea', russian: 'море', examples: [{ sentence: 'We spent vacation at the sea.', translation: 'Мы провели отпуск на море.' }] },
  { english: 'lake', russian: 'озеро', examples: [{ sentence: 'The lake is very deep.', translation: 'Озеро очень глубокое.' }] },
  { english: 'forest', russian: 'лес', examples: [{ sentence: 'The forest is full of animals.', translation: 'Лес полон животных.' }] },
  { english: 'desert', russian: 'пустыня', examples: [{ sentence: 'Deserts are very hot and dry.', translation: 'Пустыни очень жаркие и сухие.' }] },
  { english: 'island', russian: 'остров', examples: [{ sentence: 'We visited a tropical island.', translation: 'Мы посетили тропический остров.' }] },
  { english: 'valley', russian: 'долина', examples: [{ sentence: 'The valley is between two mountains.', translation: 'Долина находится между двух гор.' }] },
  { english: 'hill', russian: 'холм', examples: [{ sentence: 'We climbed the hill.', translation: 'Мы забрались на холм.' }] },
  { english: 'cliff', russian: 'утес', examples: [{ sentence: 'The cliff overlooks the sea.', translation: 'Утес возвышается над морем.' }] },
  { english: 'beach', russian: 'пляж', examples: [{ sentence: 'The beach has white sand.', translation: 'На пляже белый песок.' }] },
  { english: 'coast', russian: 'побережье', examples: [{ sentence: 'We drove along the coast.', translation: 'Мы ехали вдоль побережья.' }] },
  { english: 'waterfall', russian: 'водопад', examples: [{ sentence: 'Niagara Falls is a famous waterfall.', translation: 'Ниагарский водопад знаменит.' }] },
  { english: 'cave', russian: 'пещера', examples: [{ sentence: 'The cave is very dark inside.', translation: 'В пещере очень темно.' }] },
  { english: 'volcano', russian: 'вулкан', examples: [{ sentence: 'The volcano erupted last year.', translation: 'Вулкан извергался в прошлом году.' }] },
  { english: 'glacier', russian: 'ледник', examples: [{ sentence: 'Glaciers are melting due to climate change.', translation: 'Ледники тают из-за изменения климата.' }] },
  { english: 'jungle', russian: 'джунгли', examples: [{ sentence: 'Jungles have dense vegetation.', translation: 'В джунглях густая растительность.' }] },
  { english: 'swamp', russian: 'болото', examples: [{ sentence: 'Swamps are wet and muddy.', translation: 'Болота влажные и грязные.' }] },
  { english: 'meadow', russian: 'луг', examples: [{ sentence: 'The meadow is full of flowers.', translation: 'Луг полон цветов.' }] },
  { english: 'plain', russian: 'равнина', examples: [{ sentence: 'Plains are flat areas of land.', translation: 'Равнины - это плоские участки земли.' }] },
  { english: 'plateau', russian: 'плато', examples: [{ sentence: 'The plateau is high and flat.', translation: 'Плато высокое и плоское.' }] },
  { english: 'canyon', russian: 'каньон', examples: [{ sentence: 'The Grand Canyon is in Arizona.', translation: 'Гранд-Каньон находится в Аризоне.' }] },
  { english: 'peninsula', russian: 'полуостров', examples: [{ sentence: 'Italy is a peninsula.', translation: 'Италия - полуостров.' }] },
  { english: 'bay', russian: 'залив', examples: [{ sentence: 'Ships anchor in the bay.', translation: 'Корабли стоят на якоре в заливе.' }] },
  { english: 'strait', russian: 'пролив', examples: [{ sentence: 'The strait connects two seas.', translation: 'Пролив соединяет два моря.' }] },
  { english: 'continent', russian: 'континент', examples: [{ sentence: 'There are seven continents.', translation: 'Существует семь континентов.' }] },
  { english: 'country', russian: 'страна', examples: [{ sentence: 'Russia is the largest country.', translation: 'Россия - самая большая страна.' }] },
  { english: 'city', russian: 'город', examples: [{ sentence: 'Moscow is a big city.', translation: 'Москва - большой город.' }] },
  { english: 'village', russian: 'деревня', examples: [{ sentence: 'My grandmother lives in a village.', translation: 'Моя бабушка живет в деревне.' }] },
  { english: 'town', russian: 'городок', examples: [{ sentence: 'This is a small town.', translation: 'Это маленький городок.' }] },
  { english: 'capital', russian: 'столица', examples: [{ sentence: 'Paris is the capital of France.', translation: 'Париж - столица Франции.' }] },
  { english: 'border', russian: 'граница', examples: [{ sentence: 'We crossed the border.', translation: 'Мы пересекли границу.' }] },
  { english: 'north', russian: 'север', examples: [{ sentence: 'Canada is to the north.', translation: 'Канада находится на севере.' }] },
  { english: 'south', russian: 'юг', examples: [{ sentence: 'Birds fly south in winter.', translation: 'Птицы летят на юг зимой.' }] },
  { english: 'east', russian: 'восток', examples: [{ sentence: 'The sun rises in the east.', translation: 'Солнце встает на востоке.' }] },
  { english: 'west', russian: 'запад', examples: [{ sentence: 'The sun sets in the west.', translation: 'Солнце садится на западе.' }] },
  { english: 'equator', russian: 'экватор', examples: [{ sentence: 'The equator divides Earth in half.', translation: 'Экватор делит Землю пополам.' }] },
  { english: 'pole', russian: 'полюс', examples: [{ sentence: 'The North Pole is very cold.', translation: 'На Северном полюсе очень холодно.' }] },
  { english: 'climate', russian: 'климат', examples: [{ sentence: 'The climate is changing.', translation: 'Климат меняется.' }] },
  { english: 'weather', russian: 'погода', examples: [{ sentence: 'The weather is nice today.', translation: 'Сегодня хорошая погода.' }] },
  { english: 'temperature', russian: 'температура', examples: [{ sentence: 'The temperature dropped.', translation: 'Температура упала.' }] },
  { english: 'rain', russian: 'дождь', examples: [{ sentence: 'It will rain tomorrow.', translation: 'Завтра будет дождь.' }] },
  { english: 'snow', russian: 'снег', examples: [{ sentence: 'Snow is falling outside.', translation: 'На улице падает снег.' }] },
  { english: 'wind', russian: 'ветер', examples: [{ sentence: 'The wind is strong today.', translation: 'Сегодня сильный ветер.' }] },
  { english: 'storm', russian: 'шторм', examples: [{ sentence: 'A storm is coming.', translation: 'Приближается шторм.' }] },
  { english: 'cloud', russian: 'облако', examples: [{ sentence: 'The sky is full of clouds.', translation: 'Небо полно облаков.' }] },
  { english: 'sun', russian: 'солнце', examples: [{ sentence: 'The sun is shining brightly.', translation: 'Солнце ярко светит.' }] },
  { english: 'moon', russian: 'луна', examples: [{ sentence: 'The full moon is beautiful.', translation: 'Полная луна красива.' }] },
  { english: 'star', russian: 'звезда', examples: [{ sentence: 'Stars twinkle at night.', translation: 'Звезды мерцают ночью.' }] },
  { english: 'earth', russian: 'земля', examples: [{ sentence: 'Earth is our planet.', translation: 'Земля - наша планета.' }] },
  { english: 'sky', russian: 'небо', examples: [{ sentence: 'The sky is blue.', translation: 'Небо голубое.' }] },
  { english: 'horizon', russian: 'горизонт', examples: [{ sentence: 'The ship disappeared over the horizon.', translation: 'Корабль скрылся за горизонтом.' }] },
  { english: 'sunset', russian: 'закат', examples: [{ sentence: 'The sunset was beautiful.', translation: 'Закат был красивым.' }] },
  { english: 'sunrise', russian: 'рассвет', examples: [{ sentence: 'We watched the sunrise.', translation: 'Мы наблюдали рассвет.' }] },
  { english: 'rainbow', russian: 'радуга', examples: [{ sentence: 'A rainbow appeared after the rain.', translation: 'После дождя появилась радуга.' }] },
  { english: 'fog', russian: 'туман', examples: [{ sentence: 'The fog is very thick.', translation: 'Туман очень густой.' }] },
  { english: 'ice', russian: 'лед', examples: [{ sentence: 'The lake is covered with ice.', translation: 'Озеро покрыто льдом.' }] },
  { english: 'flood', russian: 'наводнение', examples: [{ sentence: 'The flood destroyed many homes.', translation: 'Наводнение разрушило много домов.' }] },
  { english: 'drought', russian: 'засуха', examples: [{ sentence: 'The drought lasted for months.', translation: 'Засуха длилась месяцами.' }] },
  { english: 'earthquake', russian: 'землетрясение', examples: [{ sentence: 'An earthquake hit the city.', translation: 'Землетрясение ударило по городу.' }] },
  { english: 'tsunami', russian: 'цунами', examples: [{ sentence: 'The tsunami was devastating.', translation: 'Цунами было разрушительным.' }] },
  { english: 'hurricane', russian: 'ураган', examples: [{ sentence: 'The hurricane caused damage.', translation: 'Ураган нанес ущерб.' }] },
  { english: 'tornado', russian: 'торнадо', examples: [{ sentence: 'A tornado touched down.', translation: 'Торнадо опустилось на землю.' }] },
  { english: 'reef', russian: 'риф', examples: [{ sentence: 'Coral reefs are colorful.', translation: 'Коралловые рифы красочные.' }] },
  { english: 'spring', russian: 'родник', examples: [{ sentence: 'Fresh water flows from the spring.', translation: 'Пресная вода течет из родника.' }] },
  { english: 'stream', russian: 'ручей', examples: [{ sentence: 'A small stream runs through the forest.', translation: 'Маленький ручей течет через лес.' }] },
  { english: 'pond', russian: 'пруд', examples: [{ sentence: 'Ducks swim in the pond.', translation: 'Утки плавают в пруду.' }] },
  { english: 'oasis', russian: 'оазис', examples: [{ sentence: 'An oasis is a green spot in the desert.', translation: 'Оазис - зеленое место в пустыне.' }] },
  { english: 'tundra', russian: 'тундра', examples: [{ sentence: 'The tundra is frozen most of the year.', translation: 'Тундра замерзшая большую часть года.' }] },
  { english: 'savanna', russian: 'саванна', examples: [{ sentence: 'Lions live in the savanna.', translation: 'Львы живут в саванне.' }] },
  { english: 'steppe', russian: 'степь', examples: [{ sentence: 'The steppe is a vast grassland.', translation: 'Степь - обширная равнина.' }] },
  { english: 'taiga', russian: 'тайга', examples: [{ sentence: 'The taiga has many coniferous trees.', translation: 'В тайге много хвойных деревьев.' }] },
  { english: 'wetland', russian: 'заболоченная местность', examples: [{ sentence: 'Wetlands are important ecosystems.', translation: 'Заболоченные территории - важные экосистемы.' }] },
  { english: 'delta', russian: 'дельта', examples: [{ sentence: 'The Nile delta is very fertile.', translation: 'Дельта Нила очень плодородна.' }] },
  { english: 'lagoon', russian: 'лагуна', examples: [{ sentence: 'The lagoon has clear blue water.', translation: 'В лагуне чистая голубая вода.' }] },
  { english: 'archipelago', russian: 'архипелаг', examples: [{ sentence: 'Indonesia is an archipelago.', translation: 'Индонезия - архипелаг.' }] },
  { english: 'cape', russian: 'мыс', examples: [{ sentence: 'Cape Horn is at the tip of South America.', translation: 'Мыс Горн находится на оконечности Южной Америки.' }] },
  { english: 'gulf', russian: 'залив', examples: [{ sentence: 'The Gulf of Mexico is warm.', translation: 'Мексиканский залив теплый.' }] },
  { english: 'terrain', russian: 'местность', examples: [{ sentence: 'The terrain is rough.', translation: 'Местность неровная.' }] },
  { english: 'landscape', russian: 'ландшафт', examples: [{ sentence: 'The landscape is beautiful.', translation: 'Ландшафт красивый.' }] },
  { english: 'nature', russian: 'природа', examples: [{ sentence: 'I love nature.', translation: 'Я люблю природу.' }] },
  { english: 'environment', russian: 'окружающая среда', examples: [{ sentence: 'We must protect the environment.', translation: 'Мы должны защищать окружающую среду.' }] },
  { english: 'ecology', russian: 'экология', examples: [{ sentence: 'Ecology studies ecosystems.', translation: 'Экология изучает экосистемы.' }] },
  { english: 'latitude', russian: 'широта', examples: [{ sentence: 'The latitude determines the climate.', translation: 'Широта определяет климат.' }] },
  { english: 'longitude', russian: 'долгота', examples: [{ sentence: 'Longitude lines run north to south.', translation: 'Линии долготы идут с севера на юг.' }] },
  { english: 'altitude', russian: 'высота', examples: [{ sentence: 'The altitude affects the temperature.', translation: 'Высота влияет на температуру.' }] },
  { english: 'map', russian: 'карта', examples: [{ sentence: 'I need a map to find the way.', translation: 'Мне нужна карта, чтобы найти дорогу.' }] },
  { english: 'compass', russian: 'компас', examples: [{ sentence: 'The compass points north.', translation: 'Компас указывает на север.' }] },
  { english: 'territory', russian: 'территория', examples: [{ sentence: 'The territory is large.', translation: 'Территория большая.' }] },
  { english: 'region', russian: 'регион', examples: [{ sentence: 'This region is famous for wine.', translation: 'Этот регион известен вином.' }] },
  { english: 'area', russian: 'область', examples: [{ sentence: 'The area is densely populated.', translation: 'Область густо населена.' }] },
  { english: 'zone', russian: 'зона', examples: [{ sentence: 'This is a time zone.', translation: 'Это часовой пояс.' }] },
  { english: 'hemisphere', russian: 'полушарие', examples: [{ sentence: 'Australia is in the Southern Hemisphere.', translation: 'Австралия находится в Южном полушарии.' }] },
  { english: 'population', russian: 'население', examples: [{ sentence: 'The population is growing.', translation: 'Население растет.' }] },
  { english: 'immigration', russian: 'иммиграция', examples: [{ sentence: 'Immigration has increased.', translation: 'Иммиграция увеличилась.' }] },
  { english: 'urban', russian: 'городской', examples: [{ sentence: 'Urban areas are crowded.', translation: 'Городские районы переполнены.' }] },
  { english: 'rural', russian: 'сельский', examples: [{ sentence: 'Rural life is peaceful.', translation: 'Сельская жизнь спокойная.' }] },
];

const homeWords: WordData[] = [
  { english: 'kitchen', russian: 'кухня', examples: [{ sentence: 'I cook in the kitchen.', translation: 'Я готовлю на кухне.' }] },
  { english: 'bedroom', russian: 'спальня', examples: [{ sentence: 'My bedroom is upstairs.', translation: 'Моя спальня наверху.' }] },
  { english: 'bathroom', russian: 'ванная', examples: [{ sentence: 'The bathroom has a shower.', translation: 'В ванной есть душ.' }] },
  { english: 'living room', russian: 'гостиная', examples: [{ sentence: 'We watch TV in the living room.', translation: 'Мы смотрим телевизор в гостиной.' }] },
  { english: 'dining room', russian: 'столовая', examples: [{ sentence: 'We eat dinner in the dining room.', translation: 'Мы ужинаем в столовой.' }] },
  { english: 'garage', russian: 'гараж', examples: [{ sentence: 'The car is in the garage.', translation: 'Машина в гараже.' }] },
  { english: 'garden', russian: 'сад', examples: [{ sentence: 'Flowers bloom in the garden.', translation: 'В саду цветут цветы.' }] },
  { english: 'balcony', russian: 'балкон', examples: [{ sentence: 'I have plants on my balcony.', translation: 'У меня есть растения на балконе.' }] },
  { english: 'attic', russian: 'чердак', examples: [{ sentence: 'Old boxes are stored in the attic.', translation: 'Старые коробки хранятся на чердаке.' }] },
  { english: 'basement', russian: 'подвал', examples: [{ sentence: 'The basement is cold.', translation: 'В подвале холодно.' }] },
  { english: 'door', russian: 'дверь', examples: [{ sentence: 'Please close the door.', translation: 'Пожалуйста, закрой дверь.' }] },
  { english: 'window', russian: 'окно', examples: [{ sentence: 'Open the window for fresh air.', translation: 'Открой окно для свежего воздуха.' }] },
  { english: 'wall', russian: 'стена', examples: [{ sentence: 'Hang the picture on the wall.', translation: 'Повесь картину на стену.' }] },
  { english: 'floor', russian: 'пол', examples: [{ sentence: 'The floor is made of wood.', translation: 'Пол сделан из дерева.' }] },
  { english: 'ceiling', russian: 'потолок', examples: [{ sentence: 'The ceiling is very high.', translation: 'Потолок очень высокий.' }] },
  { english: 'roof', russian: 'крыша', examples: [{ sentence: 'The roof needs repair.', translation: 'Крышу нужно отремонтировать.' }] },
  { english: 'stairs', russian: 'лестница', examples: [{ sentence: 'Be careful on the stairs.', translation: 'Будь осторожен на лестнице.' }] },
  { english: 'table', russian: 'стол', examples: [{ sentence: 'Put the book on the table.', translation: 'Положи книгу на стол.' }] },
  { english: 'chair', russian: 'стул', examples: [{ sentence: 'Sit on the chair.', translation: 'Сядь на стул.' }] },
  { english: 'sofa', russian: 'диван', examples: [{ sentence: 'The sofa is comfortable.', translation: 'Диван удобный.' }] },
  { english: 'bed', russian: 'кровать', examples: [{ sentence: 'The bed is soft.', translation: 'Кровать мягкая.' }] },
  { english: 'wardrobe', russian: 'шкаф', examples: [{ sentence: 'My clothes are in the wardrobe.', translation: 'Моя одежда в шкафу.' }] },
  { english: 'drawer', russian: 'ящик', examples: [{ sentence: 'Keys are in the drawer.', translation: 'Ключи в ящике.' }] },
  { english: 'shelf', russian: 'полка', examples: [{ sentence: 'Books are on the shelf.', translation: 'Книги на полке.' }] },
  { english: 'lamp', russian: 'лампа', examples: [{ sentence: 'Turn on the lamp.', translation: 'Включи лампу.' }] },
  { english: 'mirror', russian: 'зеркало', examples: [{ sentence: 'I looked in the mirror.', translation: 'Я посмотрел в зеркало.' }] },
  { english: 'carpet', russian: 'ковер', examples: [{ sentence: 'The carpet is soft.', translation: 'Ковер мягкий.' }] },
  { english: 'curtain', russian: 'занавеска', examples: [{ sentence: 'Close the curtains.', translation: 'Закрой занавески.' }] },
  { english: 'pillow', russian: 'подушка', examples: [{ sentence: 'The pillow is fluffy.', translation: 'Подушка пушистая.' }] },
  { english: 'blanket', russian: 'одеяло', examples: [{ sentence: 'Cover yourself with a blanket.', translation: 'Укройся одеялом.' }] },
  { english: 'refrigerator', russian: 'холодильник', examples: [{ sentence: 'Put the milk in the refrigerator.', translation: 'Положи молоко в холодильник.' }] },
  { english: 'stove', russian: 'плита', examples: [{ sentence: 'Cook on the stove.', translation: 'Готовь на плите.' }] },
  { english: 'oven', russian: 'духовка', examples: [{ sentence: 'Bake the cake in the oven.', translation: 'Выпекай торт в духовке.' }] },
  { english: 'microwave', russian: 'микроволновка', examples: [{ sentence: 'Heat the food in the microwave.', translation: 'Разогрей еду в микроволновке.' }] },
  { english: 'sink', russian: 'раковина', examples: [{ sentence: 'Wash dishes in the sink.', translation: 'Мой посуду в раковине.' }] },
  { english: 'faucet', russian: 'кран', examples: [{ sentence: 'Turn off the faucet.', translation: 'Закрой кран.' }] },
  { english: 'toilet', russian: 'унитаз', examples: [{ sentence: 'The toilet is clean.', translation: 'Унитаз чистый.' }] },
  { english: 'shower', russian: 'душ', examples: [{ sentence: 'I take a shower every morning.', translation: 'Я принимаю душ каждое утро.' }] },
  { english: 'bathtub', russian: 'ванна', examples: [{ sentence: 'Fill the bathtub with water.', translation: 'Наполни ванну водой.' }] },
  { english: 'towel', russian: 'полотенце', examples: [{ sentence: 'Dry yourself with a towel.', translation: 'Вытрись полотенцем.' }] },
  { english: 'soap', russian: 'мыло', examples: [{ sentence: 'Wash your hands with soap.', translation: 'Мой руки с мылом.' }] },
  { english: 'toothbrush', russian: 'зубная щетка', examples: [{ sentence: 'I need a new toothbrush.', translation: 'Мне нужна новая зубная щетка.' }] },
  { english: 'toothpaste', russian: 'зубная паста', examples: [{ sentence: 'Put toothpaste on the brush.', translation: 'Нанеси зубную пасту на щетку.' }] },
  { english: 'comb', russian: 'расческа', examples: [{ sentence: 'Comb your hair.', translation: 'Расчеши волосы.' }] },
  { english: 'key', russian: 'ключ', examples: [{ sentence: 'I lost my key.', translation: 'Я потерял свой ключ.' }] },
  { english: 'lock', russian: 'замок', examples: [{ sentence: 'Lock the door.', translation: 'Запри дверь.' }] },
  { english: 'doorbell', russian: 'дверной звонок', examples: [{ sentence: 'The doorbell rang.', translation: 'Дверной звонок зазвонил.' }] },
  { english: 'mailbox', russian: 'почтовый ящик', examples: [{ sentence: 'Check the mailbox.', translation: 'Проверь почтовый ящик.' }] },
  { english: 'fence', russian: 'забор', examples: [{ sentence: 'The fence is new.', translation: 'Забор новый.' }] },
  { english: 'gate', russian: 'ворота', examples: [{ sentence: 'Open the gate.', translation: 'Открой ворота.' }] },
  { english: 'porch', russian: 'крыльцо', examples: [{ sentence: 'Wait on the porch.', translation: 'Подожди на крыльце.' }] },
  { english: 'hallway', russian: 'коридор', examples: [{ sentence: 'The hallway is narrow.', translation: 'Коридор узкий.' }] },
  { english: 'closet', russian: 'кладовка', examples: [{ sentence: 'The vacuum is in the closet.', translation: 'Пылесос в кладовке.' }] },
  { english: 'fireplace', russian: 'камин', examples: [{ sentence: 'The fireplace is warm.', translation: 'У камина тепло.' }] },
  { english: 'chimney', russian: 'дымоход', examples: [{ sentence: 'Smoke comes from the chimney.', translation: 'Из дымохода идет дым.' }] },
  { english: 'furniture', russian: 'мебель', examples: [{ sentence: 'We bought new furniture.', translation: 'Мы купили новую мебель.' }] },
  { english: 'dishwasher', russian: 'посудомоечная машина', examples: [{ sentence: 'Load the dishwasher.', translation: 'Загрузи посудомоечную машину.' }] },
  { english: 'washing machine', russian: 'стиральная машина', examples: [{ sentence: 'The washing machine is running.', translation: 'Стиральная машина работает.' }] },
  { english: 'dryer', russian: 'сушилка', examples: [{ sentence: 'Put clothes in the dryer.', translation: 'Положи одежду в сушилку.' }] },
  { english: 'iron', russian: 'утюг', examples: [{ sentence: 'Iron the shirt.', translation: 'Погладь рубашку.' }] },
  { english: 'vacuum cleaner', russian: 'пылесос', examples: [{ sentence: 'Use the vacuum cleaner.', translation: 'Используй пылесос.' }] },
  { english: 'broom', russian: 'метла', examples: [{ sentence: 'Sweep with the broom.', translation: 'Подмети метлой.' }] },
  { english: 'mop', russian: 'швабра', examples: [{ sentence: 'Mop the floor.', translation: 'Помой пол шваброй.' }] },
  { english: 'bucket', russian: 'ведро', examples: [{ sentence: 'Fill the bucket with water.', translation: 'Наполни ведро водой.' }] },
  { english: 'trash can', russian: 'мусорное ведро', examples: [{ sentence: 'Throw it in the trash can.', translation: 'Выброси это в мусорное ведро.' }] },
  { english: 'light switch', russian: 'выключатель', examples: [{ sentence: 'Turn on the light switch.', translation: 'Включи выключатель.' }] },
  { english: 'outlet', russian: 'розетка', examples: [{ sentence: 'Plug it into the outlet.', translation: 'Подключи это к розетке.' }] },
  { english: 'air conditioner', russian: 'кондиционер', examples: [{ sentence: 'Turn on the air conditioner.', translation: 'Включи кондиционер.' }] },
  { english: 'heater', russian: 'обогреватель', examples: [{ sentence: 'The heater is on.', translation: 'Обогреватель включен.' }] },
  { english: 'fan', russian: 'вентилятор', examples: [{ sentence: 'The fan cools the room.', translation: 'Вентилятор охлаждает комнату.' }] },
  { english: 'radiator', russian: 'батарея', examples: [{ sentence: 'The radiator is hot.', translation: 'Батарея горячая.' }] },
  { english: 'thermostat', russian: 'термостат', examples: [{ sentence: 'Adjust the thermostat.', translation: 'Отрегулируй термостат.' }] },
  { english: 'alarm clock', russian: 'будильник', examples: [{ sentence: 'Set the alarm clock.', translation: 'Поставь будильник.' }] },
  { english: 'television', russian: 'телевизор', examples: [{ sentence: 'Watch television.', translation: 'Смотри телевизор.' }] },
  { english: 'remote control', russian: 'пульт', examples: [{ sentence: 'Pass me the remote control.', translation: 'Передай мне пульт.' }] },
  { english: 'computer', russian: 'компьютер', examples: [{ sentence: 'Work on the computer.', translation: 'Работай за компьютером.' }] },
  { english: 'desk', russian: 'письменный стол', examples: [{ sentence: 'Study at the desk.', translation: 'Занимайся за письменным столом.' }] },
  { english: 'bookcase', russian: 'книжный шкаф', examples: [{ sentence: 'Books are in the bookcase.', translation: 'Книги в книжном шкафу.' }] },
  { english: 'couch', russian: 'кушетка', examples: [{ sentence: 'Lie on the couch.', translation: 'Ляг на кушетку.' }] },
  { english: 'armchair', russian: 'кресло', examples: [{ sentence: 'Sit in the armchair.', translation: 'Сядь в кресло.' }] },
  { english: 'nightstand', russian: 'тумбочка', examples: [{ sentence: 'Put the phone on the nightstand.', translation: 'Положи телефон на тумбочку.' }] },
  { english: 'mattress', russian: 'матрас', examples: [{ sentence: 'The mattress is firm.', translation: 'Матрас жесткий.' }] },
  { english: 'sheet', russian: 'простыня', examples: [{ sentence: 'Change the sheets.', translation: 'Поменяй простыни.' }] },
  { english: 'duvet', russian: 'пуховое одеяло', examples: [{ sentence: 'The duvet is warm.', translation: 'Пуховое одеяло теплое.' }] },
  { english: 'rug', russian: 'коврик', examples: [{ sentence: 'Wipe your feet on the rug.', translation: 'Вытри ноги о коврик.' }] },
  { english: 'vase', russian: 'ваза', examples: [{ sentence: 'Put flowers in the vase.', translation: 'Поставь цветы в вазу.' }] },
  { english: 'picture frame', russian: 'рамка для фото', examples: [{ sentence: 'The picture frame is silver.', translation: 'Рамка для фото серебряная.' }] },
  { english: 'clock', russian: 'часы', examples: [{ sentence: 'The clock is on the wall.', translation: 'Часы на стене.' }] },
  { english: 'candle', russian: 'свеча', examples: [{ sentence: 'Light the candle.', translation: 'Зажги свечу.' }] },
  { english: 'plant', russian: 'растение', examples: [{ sentence: 'Water the plant.', translation: 'Полей растение.' }] },
  { english: 'housework', russian: 'домашняя работа', examples: [{ sentence: 'I do housework on weekends.', translation: 'Я делаю домашнюю работу по выходным.' }] },
  { english: 'chores', russian: 'домашние обязанности', examples: [{ sentence: 'Finish your chores.', translation: 'Закончи свои домашние обязанности.' }] },
  { english: 'rent', russian: 'аренда', examples: [{ sentence: 'Pay the rent on time.', translation: 'Плати аренду вовремя.' }] },
  { english: 'neighbor', russian: 'сосед', examples: [{ sentence: 'My neighbor is friendly.', translation: 'Мой сосед дружелюбный.' }] },
  { english: 'apartment', russian: 'квартира', examples: [{ sentence: 'I live in an apartment.', translation: 'Я живу в квартире.' }] },
  { english: 'house', russian: 'дом', examples: [{ sentence: 'This house is big.', translation: 'Этот дом большой.' }] },
];

async function main() {
  console.log('Seeding database...');

  // Create categories
  const animalsCategory = await prisma.category.upsert({
    where: { name: 'animals' },
    update: {},
    create: {
      name: 'animals',
      displayName: 'Животные',
      iconEmoji: '🐾',
    },
  });

  const geographyCategory = await prisma.category.upsert({
    where: { name: 'geography' },
    update: {},
    create: {
      name: 'geography',
      displayName: 'География',
      iconEmoji: '🌍',
    },
  });

  const homeCategory = await prisma.category.upsert({
    where: { name: 'home' },
    update: {},
    create: {
      name: 'home',
      displayName: 'Дом',
      iconEmoji: '🏠',
    },
  });

  console.log('Categories created');

  // Seed words for each category
  const categories = [
    { category: animalsCategory, words: animalsWords },
    { category: geographyCategory, words: geographyWords },
    { category: homeCategory, words: homeWords },
  ];

  for (const { category, words } of categories) {
    console.log(`Seeding ${category.name} words...`);

    for (const wordData of words) {
      await prisma.word.upsert({
        where: {
          english_categoryId: {
            english: wordData.english,
            categoryId: category.id,
          },
        },
        update: {},
        create: {
          english: wordData.english,
          russian: wordData.russian,
          categoryId: category.id,
          examples: {
            create: wordData.examples.map((ex) => ({
              sentence: ex.sentence,
              translation: ex.translation || null,
            })),
          },
        },
      });
    }

    console.log(`${words.length} ${category.name} words seeded`);
  }

  console.log('Database seeded successfully!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
